services:
    php:
        container_name: www_sample_php
        build: ./php
        volumes:
            - ./php/data:/var/www/html
        ports:
            - "80:80"
        networks:
            - php-postgres
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        container_name: www_sample_postgres
        image: postgres:16.6
        environment:
            POSTGRES_DB: "sample_db"
            POSTGRES_USER: "admin_db"
            POSTGRES_PASSWORD: "123456"
            TZ: "Asia/Vladivostok"
        volumes:
            - ./sql/init:/docker-entrypoint-initdb.d # Для создания тестовой БД
            - ./sql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - php-postgres
        restart: unless-stopped

networks:
    php-postgres:
